### ISSUE TITLE
SplitMix or TFGen as a better fast splittable random generator

### ISSUE THREAD

**Issue by moodmosaic** [jystic/dotnet-jack#26]
Perhaps, dotnet-jack could benefit from using [SplitMix](https://www.researchgate.net/profile/Doug_Lea/publication/273188325_Fast_Splittable_Pseudorandom_Number_Generators/links/57bcd2e008ae37ee394a6f92.pdf) (or even [TFGen](http://publications.lib.chalmers.se/records/fulltext/183348/local_183348.pdf)<sup>1</sup>?), since the current splittable random number generator seems to have known issues, as shown [here](https://www.reddit.com/r/haskell/comments/3x15sm/why_is_the_first_random_value_produced_from_a/), [here](https://github.com/haskell/random/issues/31), and [here](https://ghc.haskell.org/trac/summer-of-code/ticket/1674).

---

<sup>1</sup> In fact, [QuickCheck 2 provides a wrapper around either TFGen or StdGen](https://hackage.haskell.org/package/QuickCheck-2.9.2/docs/src/Test-QuickCheck-Random.html#QCGen).

**Comment by jystic** [comment]
I actually started porting [tf-random](https://hackage.haskell.org/package/tf-random) when I first started on this but I it seemed like it was a pretty big task in and of itself.

Would definitely like to move to something like TFGen in the long run though!

**Comment by moodmosaic** [comment]
I think I'll give SplitMix a shot, sooner or later, by porting it from the [original paper](https://www.researchgate.net/profile/Doug_Lea/publication/273188325_Fast_Splittable_Pseudorandom_Number_Generators/links/57bcd2e008ae37ee394a6f92.pdf), or maybe from [here](https://github.com/nkartashov/SplitMix).

**Comment by jystic** [comment]
Whether it's SplitMix or TFGen, I am keen!

I'm going to be focusing on porting the rest of the functionality I have in haskell/purescript and making sure it works nicely in F#, so I'd be happy to take a PR whether you want to do it in a separate library or in this one, up to you.

**Comment by moodmosaic** [comment]
It'll be nice having it in this one, if the implementation is reasonable small. One less external dependency 😃

**Comment by jystic** [comment]
I'm actually surprised the core of that Haskell SplitMix implementation is in C, looking at the code it seems to be things that should run fast enough in Haskell.

[This](https://github.com/nkartashov/SplitMix/blob/master/cbits/src/math_operations.c#L62-L69) is particularly odd as it would be faster in Haskell. There's an existing [popCount](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Bits.html#v:popCount) instruction in Data.Bits which compiles to a single x86 instruction.

**Comment by moodmosaic** [comment]
Now I'm wondering what happens inside the Java implementation as well, but have yet to read the paper...

**Comment by moodmosaic** [comment]
[This](https://github.com/moodmosaic/dotnet-jack/commit/66655e0702af395a4ce52dbfa020ebe16a1ca760) is where I am. – I think, some adjustments to the `nextBigInt` are warranted, and then I may open a PR.

**Comment by moodmosaic** [comment]
I've now opened #44.

**Comment by cartazio** [comment]
Pcg random is pretty good too. Easiest to setup right.  I'm hoping to have a cleaned up splitmix inbshape soon

**Comment by moodmosaic** [comment]
@cartazio, what is pcg?

For SplitMix, it's done in #44, so feel free to check it out and add comments there 😀

**Comment by moodmosaic** [comment]
>@cartazio, what is pcg?

I guess, [PCG, A Family of Better Random Number Generators](http://www.pcg-random.org/).

**Comment by moodmosaic** [comment]
@cartazio 

>Pcg random is pretty good too. Easiest to setup right.

I would disagree here. If you look at the PGC source code, [*pcg-c-basic*](https://github.com/imneme/pcg-c-basic) might look easy, but [pgc-c](https://github.com/imneme/pcg-c) and [pgc-cpp](https://github.com/imneme/pcg-cpp) can require pretty much the same effort as SplitMix.

Also
 * I don't see SplitMix being compared in [PGC's at-a-glance summary section](http://www.pcg-random.org/)
 * I'm not aware of other property-based testing tools using PGC, but I *am* for SplitMix

Still, I think it'd definitely makes sense to try out PGC and even use it as the default seed. However, since #44 is almost there, if @jystic agrees, I'd switch to SplitMix and I'd keep an eye open on PGC for the future.

**Comment by cartazio** [comment]
Splitmix is pretty well behaved even under the big crush test. Especially
if you need / want split in the API

**Comment by moodmosaic** [comment]
Closing this one since #44 is merged now.

**Comment by jystic** [comment]
@cartazio curious how you came across this project? does megacorp dabble in .NET? 😄

**Comment by cartazio** [comment]
Your ticket cited mine on the random hs project. And GitHub lists all cross
links.

How's upside down Aussie finance?

I really need to get v2 random in shape.

Ghcvm probably could be adapted to target .net rather than jvm. But that's
another topic :)
