### ISSUE TITLE
License

### ISSUE THREAD

**Issue by moodmosaic** [jystic/dotnet-jack#51]
`dotnet-jack` doesn't have an explicit licence. Should we continue with the GitHub's ([implicit](http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html))  license, or should we change the licence to something more mainstream, such as MIT License, Apache License 2.0, or GNU GPLv3?

http://choosealicense.com provides more information.

**Comment by jystic** [comment]
The PureScript version is licensed under [Apache 2.0](https://github.com/jystic/purescript-jack/blob/master/LICENSE), so I'd say we should go for that one here too.

**Comment by moodmosaic** [comment]
Yes, I'd say so too. Mostly because Jack gives you shrinking for free, otherwise I'd consider MIT or similar.

**Comment by moodmosaic** [comment]
Closing this, as it has been already resolved by #53.
